CREATE TABLE answer_C(

  ID	      VARCHAR2(20 BYTE)	PRIMARY KEY,
  ANSWER1	  NUMBER,
  ANSWER2	  NUMBER,
  ANSWER3	  NUMBER,
  ANSWER4	  NUMBER,
  ANSWER5	  NUMBER,
  ANSWER6	  NUMBER,
  ANSWER7	  NUMBER,
  ANSWER8	  NUMBER,
  ANSWER9	  NUMBER,
  ANSWER10	NUMBER

);

DESC answer_c;
