CREATE TABLE user_C(

<<<<<<< HEAD
  	ID		VARCHAR2(20 BYTE)   PRIMARY KEY,
=======
  ID		VARCHAR2(20 BYTE)   PRIMARY KEY,
>>>>>>> KimWonKeun
	NAME	VARCHAR2(10 BYTE),
	SCORE	NUMBER,
	OX		VARCHAR2(20 BYTE),
	PASS	VARCHAR2(20 BYTE),
	CNT		NUMBER
);

desc user_c;
